version: '3.8'
services:
  backend:
    container_name: stockeer-backend
    image: stockeer-backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      - DB_HOST
      - DB_PORT
      - DB_RUN_MIGRATIONS
      - DB_SYNCHRONIZE
      - BACKEND_PORT
      - JWT_SECRET
      - JWT_EXPIRATION
      - BCRYPT_HASH_ROUND
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
    restart: unless-stopped
    user: ${UID}:${GID}
    networks:
      - stockeer-frontend-backend
      - stockeer-backend-db

  frontend:
    container_name: stockeer-frontend
    image: stockeer-frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - '${FRONTEND_PORT}:80'
    restart: unless-stopped
    networks:
      - stockeer-frontend-backend
      - nginx-pm

  db:
    container_name: stockeer-db
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - stockeer-backend-db
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data

networks:
  stockeer-backend-db:
  stockeer-frontend-backend:
  nginx-pm:
#    external: true

